### ISSUE TITLE
Can't build with dotnet build

### ISSUE THREAD

**Issue by bhugot** [aienabled/WpfNetStandardSample#7]
Hello,

I can't build this project with dotnet build. Any tips on this?

Thanks

**Comment by aienabled** [comment]
Hello!

I just pushed a little fix to get rid of $(SolutionDir) as it might caused problems with building from command line.

You can build it by using `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe`.

`dotnet build` cannot build - alas, it provides a different set of props/targets and I can't easily figure out what's wrong as the diagnostic input is totally different.

Regards!
